import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
    await page.goto('http://localhost:3000/login');
    await page.getByRole('textbox', { name: 'you@university.edu' }).click();
    await page.getByRole('link', { name: 'Create one' }).click();
    await page.getByRole('textbox', { name: 'John' }).click();
    await page.getByRole('textbox', { name: 'John' }).fill('spidey');
    await page.getByRole('textbox', { name: 'Doe' }).click();
    await page.getByRole('textbox', { name: 'Doe' }).fill('Parker');
    await page.getByRole('textbox', { name: 'you@university.edu' }).click();
    await page.getByRole('textbox', { name: 'you@university.edu' }).fill('spidey@gmail.com');
    await page.getByRole('textbox', { name: 'Min. 8 characters' }).click();
    await page.getByRole('textbox', { name: 'Min. 8 characters' }).fill('spidey');
    await page.getByRole('textbox', { name: 'Min. 8 characters' }).click();
    await page.getByRole('textbox', { name: 'Min. 8 characters' }).fill('spidey@12232');
    await page.getByRole('button', { name: 'Create Account' }).click();
    await page.getByRole('button', { name: 'Year 2' }).click();
    await page.getByRole('button', { name: 'Semester 2' }).click();
    await page.getByRole('button', { name: 'Continue →' }).click();
    await page.getByRole('textbox', { name: 'e.g. CSP6001' }).click();
    await page.getByRole('textbox', { name: 'e.g. CSP6001' }).fill('SE2022');
    await page.getByRole('textbox', { name: 'e.g. Cloud Systems Programming' }).click();
    await page.getByRole('textbox', { name: 'e.g. Cloud Systems Programming' }).fill('Cloud Computing');
    await page.getByRole('button').nth(3).click();
    await page.getByRole('button', { name: 'Add Module' }).click();
    await page.getByRole('button', { name: 'Done, go to Dashboard →' }).click();
    await page.getByRole('navigation').getByText('My Goals').click();
    await page.getByRole('button', { name: '✦ Upload Lab Sheet' }).click();
    await page.locator('.goals-upload-icon').click();
    await page.getByRole('button', { name: '+ Add Manually' }).first().click();
    await page.getByRole('textbox', { name: 'e.g. Complete Lab' }).click();
    await page.getByRole('textbox', { name: 'e.g. Complete Lab' }).fill('Complete lab 7');
    await page.getByRole('textbox', { name: 'What do you need to achieve' }).click();
    await page.getByRole('textbox', { name: 'What do you need to achieve' }).fill('Lab7 - GV');
    await page.getByRole('textbox', { name: 'e.g. Y3S1' }).click();
    await page.getByRole('textbox', { name: 'e.g. Y3S1' }).fill('Y2S2');
    await page.locator('input[type="date"]').fill('2026-04-30');
    await page.getByRole('textbox', { name: 'Type a step and press Add or' }).click();
    await page.getByRole('textbox', { name: 'Type a step and press Add or' }).fill('build world');
    await page.getByRole('button', { name: '+ Add Step' }).click();
    await page.getByRole('textbox', { name: 'Type a step and press Add or' }).click();
    await page.getByRole('textbox', { name: 'Type a step and press Add or' }).fill('game physics');
    await page.getByRole('button', { name: '+ Add Step' }).click();
    await page.getByRole('button', { name: 'Create Goal' }).click();
    await page.getByRole('button', { name: 'View guidance & progress' }).click();
    await page.getByRole('button', { name: 'Mark complete' }).first().click();
    await page.getByRole('button', { name: 'Mark complete' }).click();
    await page.getByRole('button', { name: 'Complete Goal' }).click();
});